// Offline contract smoke test. Pass fixtures.json generated by the real Python
// backend with injected transport, never by running an inference benchmark.
import Foundation

func check(_ condition: @autoclosure () -> Bool, _ message: String) {
    if !condition() { fatalError(message) }
}

guard CommandLine.arguments.count == 2 else {
    fatalError("Usage: gui-protocol-smoke /path/to/backend-fixtures.json")
}
let fixtureData = try Data(contentsOf: URL(fileURLWithPath: CommandLine.arguments[1]))
let fixture = try JSONSerialization.jsonObject(with: fixtureData) as! [String: Any]
func data(_ object: Any) throws -> Data { try JSONSerialization.data(withJSONObject: object) }
let decoder = JSONDecoder()
let status = try decoder.decode(ClusterStatus.self, from: data(fixture["status"]!))
let models = try decoder.decode([ModelEntry].self, from: data(fixture["models"]!))
let snapshot = try decoder.decode(TelemetrySnapshot.self, from: data(fixture["snapshot"]!))
let runs = try decoder.decode([BenchmarkRun].self, from: data(fixture["runs"]!))
check(!models.isEmpty, "Backend model catalog should decode")
func sampleModel(_ id: String, _ label: String) -> ModelEntry {
    ModelEntry(id: id, label: label, aliases: [], served_name: id, ctx: 1, image: "image",
               notes: "", wrapper: "vllm", hermes_provider: "spark", backend: "vllm", topology: "distributed")
}
check(ModelFamily.allCases.map(\.rawValue) == ["DeepSeek", "GLM", "Qwen", "MiMo"], "Model columns stay in family order")
check(ModelFamily.of(sampleModel("ds4", "DeepSeek-V4-Flash")) == .deepSeek, "DeepSeek cards belong in the DeepSeek column")
check(ModelFamily.of(sampleModel("ds41-exl3", "DeepSeek-v4.1-Flash EXL3")) == .deepSeek, "DeepSeek V4.1 EXL3 belongs in the DeepSeek column")
check(ModelFamily.of(sampleModel("glm53", "GLM-5.3-Flash NVFP4")) == .glm, "GLM NVFP4 belongs in the GLM column")
check(ModelFamily.of(sampleModel("glm53-exl3", "GLM-5.3-Flash EXL3")) == .glm, "GLM EXL3 belongs in the GLM column")
check(ModelFamily.of(sampleModel("glm53-tensorfold", "GLM-5.3-Flash EXL3 TensorFold")) == .glm, "GLM TensorFold belongs in the GLM column")
check(ModelFamily.of(sampleModel("qwen38-dual", "Qwen3.8-Flash-Next NVFP4 dual Spark")) == .qwen, "Qwen cards belong in the Qwen column")
check(ModelFamily.of(sampleModel("mimo26", "MiMo-V2.6-Flash-RL")) == .mimo, "MiMo cards belong in the MiMo column")
check(ModelCardFacts.runtimeTitle(wrapper: "nim") == "NVIDIA NIM", "NIM cards use an NVIDIA NIM pill")
check(ModelCardFacts.runtimeTitle(wrapper: "dsv4") == "DwarfStar", "DeepSeek dsv4 cards use a DwarfStar pill")
check(ModelCardFacts.runtimeTitle(wrapper: "vllm") == "vLLM", "vLLM cards use a vLLM pill")
check(ModelCardFacts.runtimeTitle(wrapper: "tensorfold") == "TensorFold", "TensorFold cards use a TensorFold pill")
check(ModelCardFacts.contextTitle(ctx: 1_048_576, backend: "vllm") == "1M ctx", "1M context keeps its label")
check(ModelCardFacts.contextTitle(ctx: 131_072, backend: "vllm") == "128k ctx", "128k context keeps its label")
check(ModelCardFacts.contextTitle(ctx: 262_144, backend: "vllm") == "262k ctx", "262k context keeps its label")
check(ModelCardFacts.contextTitle(ctx: 300_000, backend: "vllm") == "300k ctx", "300k context is not collapsed to 262k")
check(ModelCardFacts.contextTitle(ctx: 850_000, backend: "vllm") == "850k ctx", "850k context is not collapsed to 262k")
check(ModelCardFacts.contextTitle(ctx: 600_000, backend: "vllm") == "600k ctx", "600k context keeps its label")
check(ModelCardFacts.sparkTitle(topology: "single") == "1 Spark", "Single-node cards say 1 Spark")
check(ModelCardFacts.sparkTitle(topology: "distributed") == "2 Sparks", "Two-node cards say 2 Sparks")
check(status.nodes?.count == 2, "Two physical host status rows should decode")
check(snapshot.hosts.count == 2, "Two host telemetry records should decode")
check(!runs.isEmpty, "Real saved run fixture should decode")
check(runs.allSatisfy { $0.startedDate != nil }, "Backend ISO timestamps must parse")
let oldRuntime = try decoder.decode(BenchmarkRuntime.self, from: data(["engine": "vllm", "image": "sha256:pinned"]))
check(oldRuntime.settings == nil && oldRuntime.max_model_len == nil, "Older benchmark history must decode without runtime settings")
let tensorfoldRuntime = try decoder.decode(BenchmarkRuntime.self, from: data([
    "engine": "tensorfold", "image": "sha256:pinned", "max_model_len": 262144, "settings_source": "catalog",
    "settings": ["parallel": 4, "kv_dtype": "int8", "model_revision": "pinned"],
]))
check(tensorfoldRuntime.streamsText == "4" && tensorfoldRuntime.cacheText == "int8", "TensorFold benchmark settings must decode")
check(tensorfoldRuntime.max_model_len == 262144, "TensorFold benchmark context must be retained")
check(tensorfoldRuntime.settings_source == "catalog", "Configured runtime settings must retain their source")

var benchmarkAllocation = (fixture["snapshot"] as! [String: Any])["allocations"] as! [[String: Any]]
for runtime in ["tensorfold", "vllm", "nim", "unknown"] {
    benchmarkAllocation[0]["runtime"] = runtime
    for ready in [true, false] {
        benchmarkAllocation[0]["ready"] = ready
        let allocation = try decoder.decode(AllocationTelemetry.self, from: data(benchmarkAllocation[0]))
        check(allocation.supportsBenchmark == (ready && runtime != "unknown"), "Only supported, ready runtimes may be benchmarked")
    }
}

let telemetry = TelemetryStore(home: nil)
var changing = fixture["snapshot"] as! [String: Any]
for index in 0..<400 {
    let timestamp = 1_000.0 + Double(index * 2)
    changing["timestamp"] = timestamp
    changing["hosts"] = (changing["hosts"] as! [[String: Any]]).map { original in
        var host = original
        host["sampled_at"] = timestamp
        host["state"] = "live"
        return host
    }
    telemetry.receive(try data(changing))
}
check(telemetry.history.values.allSatisfy { $0.count <= TelemetryStore.maximumPoints }, "Chart history must remain bounded")
check(telemetry.history.values.contains { $0.count == TelemetryStore.maximumPoints }, "Live history should retain its configured window")
check(telemetry.currentState("live", sampledAt: 1_798, now: Date(timeIntervalSince1970: 1_798)) == "stale", "Disconnected stream must not show live metrics")
check(!telemetry.topologyIsFresh(now: Date()), "Disconnected topology must be stale")
check(telemetry.benchmarkTargets().isEmpty, "Disconnected topology must not offer benchmark targets")

let store = BenchmarkStore(home: nil)
let firstRun = (fixture["runs"] as! [[String: Any]])[0]
var startedRun = firstRun
startedRun["status"] = "running"
startedRun.removeValue(forKey: "finished_at")
startedRun.removeValue(forKey: "summary")
startedRun["warmup"] = NSNull()
startedRun["results"] = []
store.receive(try data(["event": "started", "run": startedRun]))
check(store.current?.status == "running", "Started event without summary must decode")
store.receive(try data(["event": "result", "run": firstRun]))
check(store.current?.id == runs[0].id && store.history.count == 1, "Completed result must enter native history")
check(store.current?.config.thinking == runs[0].config.thinking, "Tri-state thinking must preserve null")

var unsupported = changing
unsupported["hosts"] = (unsupported["hosts"] as! [[String: Any]]).map { original in
    var host = original
    var resources = host["resources"] as! [String: Any]
    resources["gpu_memory_used_bytes"] = NSNull()
    host["resources"] = resources
    return host
}
telemetry.receive(try data(unsupported))
check(telemetry.snapshot?.hosts.first?.resources.gpu_memory_used_bytes == nil, "Unreported GPU memory must stay absent")
print("Native protocol smoke passed: status, telemetry, benchmark events/history, ISO dates, bounded history, stale state, null metrics.")

check(HermesTarget.local.useArguments(node: "head") == ["use", "--node", "head", "--hermes-target", "local", "--json"], "Mac Hermes must keep its local target")
check(HermesTarget.spark.useArguments(node: "worker") == ["use", "--node", "worker", "--hermes-target", "spark", "--json"], "Spark Hermes target must be separate from the model node")
